// 01-react/00-start/src/hooks/color.hooks.ts
import React from "react";
import { getPrimaryColor, setPrimaryColor } from "@/helpers";

export const useColor = () => {
  const [color, setColor] = React.useState(getPrimaryColor());

  const handleColorChange = (newColor) => {
    setColor(newColor);
    setPrimaryColor(newColor);
  };

  return {
    color,
    onColorChange: handleColorChange,
  };
};

// 02-solidjs/src/hooks/color.hooks.ts
import { createSignal } from "solid-js";
import { getPrimaryColor, setPrimaryColor } from "@/helpers";

export const useColor = () => {
  const [color, setColor] = createSignal(getPrimaryColor());

  const handleColorChange = (newColor) => {
    setColor(newColor);
    setPrimaryColor(newColor);
  };

  return {
    color,
    onColorChange: handleColorChange,
  };
};
