// 04-async-closure/02-solidjs/src/app.tsx
import { createSignal } from "solid-js";

// Can you spot what's going on?
// Below solution :)
export const App = () => {
  const [message, setMessage] = createSignal("initial message");
  const [seconds, setSeconds] = createSignal(0);

  setTimeout(() => {
    console.log(seconds());
    setSeconds(1);
  }, 1000);

  setTimeout(() => {
    setMessage(`Total seconds: ${seconds()}`);
  }, 2000);

  return (
    <>
      <h3>{message()}</h3>
      <h4>{seconds()}</h4>
    </>
  );
};

// 04-async-closure/01-react/src/app.tsx
import React from "react";

// Can you spot what's going on?
// Below solution :)
export const App = () => {
  const [message, setMessage] = React.useState("initial message");
  const [seconds, setSeconds] = React.useState(0);

  React.useEffect(() => {
    setTimeout(() => {
      console.log(seconds);
      setSeconds(1);
    }, 1000);

    setTimeout(() => {
      setMessage(`Total seconds: ${seconds}`);
    }, 2000);
  }, []);

  return (
    <>
      <h3>{message}</h3>
      <h4>{seconds}</h4>
    </>
  );
};

/*
// Working example
export const App = () => {
  const [message, setMessage] = React.useState("initial message");
  const [seconds, setSeconds] = React.useState(0);
  const secondsRef = React.useRef(seconds);

  React.useEffect(() => {
    setTimeout(() => {
      console.log(seconds);
      setSeconds(1);
      secondsRef.current = 1;
    }, 1000);

    setTimeout(() => {
      setMessage(`Total seconds: ${secondsRef.current}`);
    }, 2000);
  }, []);

  return (
    <>
      <h3>{message}</h3>
      <h4>{seconds}</h4>
    </>
  );
};
*/
