// 01-react/03-useMemo/src/components/render-count.component.tsx
import React from "react";
import classes from "./render-count.module.css";

const getClassName = (count: number) =>
  count >= 10
    ? count > 25
      ? classes.error
      : classes.warning
    : classes.success;

export const RenderCount = () => {
  const count = React.useRef(0);
  count.current = count.current + 1;
  return (
    <span className={`${classes.root} ${getClassName(count.current)}`}>
      {count.current}
    </span>
  );
};

// 02-solidjs/src/components/render-count.component.tsx
import { createSignal } from "solid-js";
import classes from "./render-count.module.css";

const getClassName = (count: number) =>
  count >= 10
    ? count > 25
      ? classes.error
      : classes.warning
    : classes.success;

export const RenderCount = () => {
  const [count, setCount] = createSignal(0);
  setCount(count() + 1);

  return (
    <span class={`${classes.root} ${getClassName(count())}`}>{count()}</span>
  );
};
