// 01-react/03-useMemo/src/components/add-product.component.tsx
import React from "react";
import type { Product } from "@/models";
import classes from "./add-product.module.css";

interface Props {
  onAdd: React.Dispatch<React.SetStateAction<Product[]>>;
}

export const AddProduct: React.FC<Props> = (props) => {
  const { onAdd } = props;

  const [name, setName] = React.useState("");

  const handleAddProduct = () => {
    if (name) {
      onAdd((products) => [
        ...products,
        {
          id: `${Math.random()}-${name}`,
          name,
          price: Number((Math.random() * 100).toFixed(2)),
          fav: false,
        },
      ]);
      setName("");
    }
  };

  return (
    <div className={classes.root}>
      <input
        placeholder="Add product"
        type="text"
        value={name}
        onChange={(e) => setName(e.target.value)}
      />
      <button type="submit" onClick={handleAddProduct}>
        Add
      </button>
    </div>
  );
};

// 03-sveltejs/src/components/add-product.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import type { Product } from "@/models";

  const dispatch = createEventDispatcher();
  const onAdd = (product: Product) => {
    dispatch("add", {
      product,
    });
  };

  let name = "";
  const handleAddProduct = () => {
    if (name) {
      onAdd({
        id: `${Math.random()}-${name}`,
        name,
        price: Number((Math.random() * 100).toFixed(2)),
        fav: false,
      });
      name = "";
    }
  };
</script>

<div class="root">
  <input placeholder="Add product" type="text" bind:value={name} />
  <button type="submit" on:click={handleAddProduct}>Add</button>
</div>

<style>
  .root {
    user-select: none;
    display: flex;
    gap: 1rem;
    align-items: center;
    justify-content: space-between;
    background-color: var(--primary-darken);
    padding: 0.3rem;
    border-radius: 15px;
  }
</style>
