// 02-solidjs/src/components/color-picker.component.tsx
import type { Component } from "solid-js";
import classes from "./color-picker.module.css";

interface Props {
  color: string;
  onChange: (color: string) => void;
}

export const ColorPicker: Component<Props> = (props) => {
  return (
    <input
      class={classes.root}
      type="color"
      value={props.color}
      onInput={(event) => props.onChange(event.currentTarget.value)}
    />
  );
};

// 01-react/02-filter/src/components/color-picker.component.tsx
import React from "react";
import classes from "./color-picker.module.css";

interface Props {
  color: string;
  onChange: (color: string) => void;
}

export const ColorPicker: React.FC<Props> = (props) => {
  const { color, onChange } = props;
  return (
    <input
      className={classes.root}
      type="color"
      value={color}
      onChange={(event) => onChange(event.currentTarget.value)}
    />
  );
};
