// 03-sveltejs/src/components/fancy-filter.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import ColorPicker from "./color-picker.svelte";
  import Icon from "./icon.svelte";
  export let color: string;
  export let visibility: string;

  const dispatch = createEventDispatcher();
  const onColorChange = (event: CustomEvent<{ color: string }>) => {
    dispatch("color-change", {
      color: event.detail.color,
    });
  };
  const onVisibilityChange = (visibility: string) => {
    dispatch("visibility-change", {
      visibility,
    });
  };

  $: getStyles = (variant: string) =>
    visibility === variant ? "color: white;" : "color: black;";
</script>

<div class="root">
  <ColorPicker {color} on:change={onColorChange} />
  <button
    type="button"
    on:click={() => onVisibilityChange("all")}
    style={getStyles("all")}
  >
    All
  </button>
  <button type="button" on:click={() => onVisibilityChange("fav")}>
    <Icon class="star fill" name="star" style={getStyles("fav")} />
  </button>
  <button type="button" on:click={() => onVisibilityChange("unfav")}>
    <Icon class="star" name="star" style={getStyles("unfav")} />
  </button>
</div>

<style>
  .root {
    display: flex;
    flex-direction: row;
    gap: 1rem;
    justify-content: space-between;
    align-items: center;
  }
</style>

// 01-react/02-filter/src/components/fancy-filter.component.tsx
import React from "react";
import { ColorPicker } from "./color-picker.component";
import { Icon } from "./icon.component";
import classes from "./fancy-filter.module.css";

interface Props {
  color: string;
  onColorChange: (color: string) => void;
  visibility: string;
  onVisibilityChange: (visibility: string) => void;
}

export const FancyFilter: React.FC<Props> = (props) => {
  const { color, onColorChange, visibility, onVisibilityChange } = props;

  const getStyles = (variant: string) =>
    visibility === variant ? { color: "white" } : { color: "black" };

  return (
    <div className={classes.root}>
      <ColorPicker color={color} onChange={onColorChange} />
      <button
        type="button"
        onClick={() => onVisibilityChange("all")}
        style={getStyles("all")}
      >
        All
      </button>
      <button type="button" onClick={() => onVisibilityChange("fav")}>
        <Icon className="star fill" name="star" style={getStyles("fav")} />
      </button>
      <button type="button" onClick={() => onVisibilityChange("unfav")}>
        <Icon className="star" name="star" style={getStyles("unfav")} />
      </button>
    </div>
  );
};
